name: AWS CLI

on:
  workflow_call:
    inputs:
      aws-region:
        required: true
        type: string
      role-arn:
        required: true
        type: string
      cli-commands:
        required: true
        type: string

jobs:
  aws-cli-commands:
    runs-on: self-hosted
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role-arn }}
          aws-region: ${{ inputs.aws-region }}

      - name: Execute AWS CLI commands
        run: |
          ${{ inputs.cli-commands }}