name: Push image to Container Registry

on:
  workflow_call:
    inputs:
      role_arn:
        required: true
        type: string
      runs_on:
        required: false
        type: string
        default: 'self-hosted'
    secrets:
      aws_region:
        required: true
      ecr_repo:
        required: true
      gh_pkg_token:
        required: true
      checkout_dir:
        required: false

permissions:
  id-token: write
  contents: read

jobs:
  push_image_to_registry:
    name: PushImage
    runs-on: ${{ inputs.runs_on }}

    env:
      ECR_REPOSITORY: ${{ secrets.ecr_repo }}

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        sparse-checkout: |
          ${{ secrets.checkout_dir }}

    - name: set-env-vars
      uses: FranzDiebold/github-env-vars-action@v2

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role_arn }}
        aws-region: ${{ secrets.aws_region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Check if image tag exists
      id: check-tag
      run: |
        echo "Starting check-tag step"
        IMAGE_TAG=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9]/-/g')
        FULL_TAG="${IMAGE_TAG}-${CI_SHA_SHORT}"
        echo "Constructed FULL_TAG: $FULL_TAG"
        echo "FULL_TAG=${FULL_TAG}" >> $GITHUB_ENV

        echo "Checking for image: $ECR_REPOSITORY:$FULL_TAG in region ${{ secrets.aws_region }}"
        if aws ecr describe-images --repository-name $ECR_REPOSITORY --image-ids imageTag=$FULL_TAG --region ${{ secrets.aws_region }}; then
          echo "Tag exists. Skipping build and push."
          echo "TAG_EXISTS=true" >> $GITHUB_ENV
        else
          echo "Tag does not exist. Proceeding with build and push."
          echo "TAG_EXISTS=false" >> $GITHUB_ENV
        fi

    - name: Build, tag, and push image to Amazon ECR
      id: build_image
      if: env.TAG_EXISTS == 'false'
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        echo "TAG_EXISTS is '${{ env.TAG_EXISTS }}'"
        echo "Building and pushing image with tag: $FULL_TAG"
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$FULL_TAG --build-arg GH_PKG_TOKEN=${{ secrets.gh_pkg_token }} .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$FULL_TAG
