# .github/workflows/deploy.yml
name: Helm Deploy

on:
  workflow_call:
    inputs:
      runs_on:
        required: false
        type: string
        default: 'self-hosted' 
      release:
        required: true
        type: string
      chart:
        required: true
        type: string
      namespace:
        required: false
        type: string
        default: 'default' 
      value-file:
        required: true
        type: string      
    secrets:
      kubeconfig:
        required: true

jobs:
  deploy_to_k8s:
    name: Deploy
    runs-on: ${{ inputs.runs_on }}

    steps:
    # Set kubeconfig context for cluster
    - name: Set Kubeconfig
      uses: azure/k8s-set-context@v2
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.kubeconfig }}

    # Helm is required to generate the manifests
    - name: Install Helm
      run: |
        wget https://get.helm.sh/helm-v3.11.0-linux-amd64.tar.gz
        tar xvf helm-v3.11.0-linux-amd64.tar.gz
        sudo mv linux-amd64/helm /usr/local/bin
        echo "Installed helm"

    - uses: azure/setup-kubectl@v3
      id: install-k8s

    - name: Install
      id: install
      continue-on-error: true
      run: |
        helm install ${{ inputs.release }} -f ${{ inputs.value-file }} ${{ inputs.chart }} --namespace ${{ inputs.namespace }}

    - name: Upgrade
      run: |
        helm upgrade ${{ inputs.release }} -f ${{ inputs.value-file }} ${{ inputs.chart }} --namespace ${{ inputs.namespace }}