name: Deploy Custom Runners

on:
  workflow_call:
    inputs:
      ecr_role_arn:
        required: false
        type: string
        default: 'arn:aws:iam::521531168981:role/gha-ecr-exec'
      ecr_repo:
        required: true
        type: string
      checkout_dir:
        required: true
        type: string
      runs_on:
        required: false
        type: string
        default: 'self-hosted'

jobs:

  build-and-push-image:
    uses: LearnWithHomer/infrastructure-public/.github/workflows/build-and-push-image-to-ecr.yml@main
    with:
      role_arn: ${{ inputs.ecr_role_arn }}
      runs_on: ${{ inputs.runs_on }}
    secrets:
      ecr_repo: ${{ inputs.ecr_repo }}
      aws_region: "us-east-1"
      gh_pkg_token: "default"
      checkout_dir: ${{ inputs.checkout_dir }}