name: Notify on Slack

on:
  workflow_call:
    inputs:
      slack_channel:
        required: true
        type: string
      app_env:
        required: true
        type: string
      runner:
        required: false
        type: string
      action_type:
        required: false
        type: string
        default: 'Deployment'
      status:
        required: false
        type: string
        default: 'SUCCESS'
      custom_message:
        required: false
        type: string
        default: ''
    secrets:
      slack_bot_token:
        required: true

jobs:
  notify_on_slack:
    name: Slack
    runs-on: ${{ inputs.runner || 'self-hosted' }}

    steps:
    - name: Notify Slack
      uses: wearerequired/slack-messaging-action@v1
      with:
        bot_token: ${{ secrets.slack_bot_token }}
        channel: ${{ inputs.slack_channel }}
        payload: >-
          {
              "icon_emoji": ":rocket:",
              "username": "Deployer",
              "attachments": [
                  {
                      "author_name": "${{ github.event.sender.login }}",
                      "author_link": "${{ github.event.sender.html_url }}",
                      "author_icon": "${{ github.event.sender.avatar_url }}",
                      "color": "${{ inputs.status == 'SUCCESS' && 'good' || 'danger' }}",
                      "fallback": "${{ inputs.action_type }} ${{ inputs.status }}",
                      "pretext": "${{ inputs.custom_message != '' && inputs.custom_message || format(':rocket: *{0} {1}*\n:link: <{2}|View details>', inputs.status, inputs.action_type, format('{0}/{1}/actions/runs/{2}', github.server_url, github.repository, github.run_id)) }}",
                      "fields": [
                          {
                            "title": "Action",
                            "value": "${{ inputs.action_type }}",
                            "short": true
                          },
                          {
                            "title": "Status",
                            "value": "${{ inputs.status }}",
                            "short": true
                          },
                          {
                            "title": "Environment",
                            "value": "${{ inputs.app_env }}",
                            "short": true
                          },
                          {
                            "title": "Branch",
                            "value": "${{ github.ref_name }}",
                            "short": true
                          },
                          {
                            "title": "Commit",
                            "value": "<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>",
                            "short": false
                          }
                        ],
                      "footer": "<https://github.com/${{ github.repository }}|${{ github.repository }}>"
                  }
              ]
          }