name: Notify on Slack

on:
  workflow_call:
    inputs:
      slack_channel:
        required: true
        type: string
      app_env:
        required: true
        type: string
      runner:
        required: false
        type: string
      custom_message:
        required: false
        type: string
        default: ''
    secrets:
      slack_bot_token:
        required: true

jobs:
  notify_on_slack:
    name: Slack
    runs-on: ${{ inputs.runner || 'self-hosted' }}

    steps:
    - name: Notify Slack Success
      uses: wearerequired/slack-messaging-action@v1
      with:
        bot_token: ${{ secrets.slack_bot_token }}
        channel: ${{ inputs.slack_channel }} # <--- Enter the right channel name here
        payload: >-
          {
              "icon_emoji": ":rocket:",
              "username": "Deployer",
              "attachments": [
                  {
                      "author_name": "${{ github.event.sender.login }}",
                      "author_link": "${{ github.event.sender.html_url }}",
                      "author_icon": "${{ github.event.sender.avatar_url }}",
                      "color": "good",
                      "fallback": "Deployment Finished",
                      "pretext": "${{ inputs.custom_message != '' && inputs.custom_message || format('SUCCESS: {0} to {1} for {2}.', github.ref_name, inputs.app_env, github.event.repository.name) }}",
                      "fields": [
                          {
                            "title": "Revision",
                            "value": "<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}@${{ github.ref }}>",
                            "short": true
                          }
                        ],
                      "footer": "<https://github.com/${{ github.repository }}|${{ github.repository }}>"
                  }
              ]
          }
